---
title: "Compile data"
author: "Anna Talucci"
date: '2022-09-29'
output: html_document
---

# Overview


# Librarys
```{r}
library(tidyverse)
```

# Data

## FWI


```{r}
fwi_bind <- list.files(path = "../data/Landscape1/fwi/", # Identify all CSV files
                       pattern = "*.csv", full.names = TRUE) %>% 
  lapply(read_csv) %>%                              # Store all files in list
  bind_rows   # bind data sets into one data set 
```

```{r}
fwi_bind 
```

## Landsat
```{r}
landsat =  list.files(path = "../data/Landscape1/Landsat/", # Identify all CSV files
                       pattern = "*.csv", full.names = TRUE) %>% 
  lapply(read_csv) %>%                              # Store all files in list
  bind_rows   # bind data sets into one data set 
```

```{r}
landsat
```

## Static
```{r}
static =  read.csv("../data/Landscape1/Static/static_test.csv", header=TRUE, sep = ",", strip.white = TRUE)
```


```{r}
static
```

# Select columns & rename to match
```{r}
static1 = static %>% 
  dplyr::select(ID1, ID2,BD_30:FIREID, NAME:pH_30) 

static1
```

```{r}
landsat1 = landsat %>% 
  dplyr::select(FIREID:wetness) 
```


```{r}
fwi1 = fwi_bind %>% 
  dplyr::select(BUI:wspeed)  
```

# Check number of IDs
```{r}
length(unique(landsat1$ID1))
length(unique(static1$ID1))
length(unique(fwi1$ID1))
```

# Combine data 
```{r}
static1
landsat1
fwi1
```

```{r}
combine1 = merge(static1, landsat1, by = c("ID1", "ID2", "NAME", "FIREID", "lat", "lon"))
```

```{r}
combine1
```

```{r}
combine2 = merge(static1, fwi1, by = c("ID1", "ID2", "NAME", "FIREID", "lat", "lon"))
```

```{r}
combine2
```

**THE END**