---
title: "Create CSV for CNA"
author: "Anna Talucci"
date: '2022-11-15'
output: html_document
---

# Overview


# Librarys
```{r}
library(tidyverse)
```

# Data

## FWI


```{r}
fwi_bind <- list.files(path = "../data/Landscape1/fwi/", # Identify all CSV files
                       pattern = "*.csv", full.names = TRUE) %>% 
  lapply(read_csv) %>%                              # Store all files in list
  bind_rows   # bind data sets into one data set 
```

```{r}
fwi_bind 
```

## Landsat
```{r}
landsat =  list.files(path = "../data/Landscape1/Landsat/", # Identify all CSV files
                       pattern = "*.csv", full.names = TRUE) %>% 
  lapply(read_csv) %>%                              # Store all files in list
  bind_rows   # bind data sets into one data set 
```

```{r}
landsat
```

## Static
```{r}
static =  read.csv("../data/Landscape1/Static/static_test.csv", header=TRUE, sep = ",", strip.white = TRUE)
```

```{r}
terrain =  read.csv("../data/Landscape1/Static/Static_terrain.csv", header=TRUE, sep = ",", strip.white = TRUE)
```

```{r}
veg =  read.csv("../data/Landscape1/Static/static_vegetation_3338.csv", header=TRUE, sep = ",", strip.white = TRUE)
```

```{r}
static
```

```{r}
veg
```

```{r}
terrain
```


## Climate NA
```{r}
cna =  read.csv("../data/Landscape1/CNA/Landscape1CLimateNAData2.csv", header=TRUE, sep = ",", strip.white = TRUE)
```

```{r}
head(cna)
```

# Select columns 
## Static
```{r}
terrain_veg = full_join(terrain, veg, by = c("ID1", "ID2", "FIREID", "NAME", "lat", "lon")) %>%
  dplyr::select(-system.index.x, -.geo.x, -system.index.y, -.geo.y)
```

```{r}
static
```
```{r}
static1 = static %>% 
  dplyr::select(-system.index, -Ruggedness, -key, -.geo) 
```

```{r}
static2 = full_join(static1, terrain_veg, by = c("ID1", "ID2", "FIREID", "NAME", "lat", "lon")) 

static2
```

## landsat
```{r}
landsat1 = landsat %>% 
  dplyr::select(FIREID:wetness) 

landsat1
```

```{r}
landsat %>%
  dplyr::select(ID1, ID2, lat, lon) %>%
  write_csv(., "../outputs/ID1ID2LatLon.csv")
```
## FWI
```{r}
fwi1 = fwi_bind %>% 
  dplyr::select(BUI:wspeed)  
```

```{r}
fwi1 %>% dplyr::select(ID1, ID2, lat, lon) %>% write_csv(., "../outputs/Landscape1ForCNAFromFWI.csv")
```

# Check number of IDs
```{r}
length(unique(landsat1$ID1))
length(unique(static2$ID1))
length(unique(fwi1$ID1))
length(unique(cna$ID1))
```

```{r}
length(unique(landsat1$ID2))
length(unique(static2$ID2))
length(unique(fwi1$ID2))
length(unique(cna$ID2))
```
# head
```{r}
fwi1
```

# Combine to figure out join issue with CNA
tibble::rowid_to_column(data, "ID")
```{r}
static_landsat = full_join(static2, landsat1, by = c("ID1", "ID2", "FIREID", "NAME", "lat", "lon")) 

static_landsat
```

```{r}
static_landsat_fwi = full_join(static_landsat, fwi1, by = c("ID1", "ID2", "FIREID", "NAME", "lat", "lon")) 

static_landsat_fwi
```


```{r}
df_for_cna1 = tibble::rowid_to_column(static_landsat_fwi, "ID") %>% 
  rename(ID1 = ID, UniqueID = ID1) 

df_for_cna2 = df_for_cna1 %>% 
  dplyr::select(ID1, ID2, lat, lon, elevation)
```

```{r}
df_for_cna2
```
# Write to csv
```{r eval=FALSE, include=FALSE}
write_csv(df_for_cna2, "../outputs/Landscape1DFforCNA.csv")
```